// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64       `json:"id"`
	UserID    pgtype.Int8 `json:"user_id"`
	PostID    pgtype.Int8 `json:"post_id"`
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	EditedAt  time.Time   `json:"edited_at"`
}

type Post struct {
	ID        int64       `json:"id"`
	UserID    pgtype.Int8 `json:"user_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Status    bool        `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	EditedAt  time.Time   `json:"edited_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Status    bool      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
